### ISSUE TITLE
BIO: Add APIs to work with Either

### ISSUE THREAD

**Issue by pakoito** [arrow-kt/arrow-fx#145]
```
fun <E, EE : E, A> IO<E, Either<E, A>>.flattenEither(): IO<E, A> =
  flatMap { it.fold(::IO.raiseError, ::IO.just) }
```

```
fun <E, A> effectEither(f: suspend () -> Either<E, A>): IO<E, A> =
  effect(f).flattenEither()
```

```
fun <E, EE: E, A, B> IO<E, A>.mapEither(f: (A) -> Either<EE, B>): IO<EE, B> =
  map(f).flattenEither()
```

```
fun <E, EE: E, A, B> IO<E, A>.effectMapEither(f: suspend (A) -> Either<EE, B>): IO<EE, B> =
  effectMap(f).flattenEither()
```

**Comment by raulraja** [comment]
Can effect and map for Either also use the same names as for the non either shape. Would this be more efficient if it's treated as a new IO node in the run loop like Effect?

**Comment by pakoito** [comment]
They cannot because the compiler cannot tell `(A) -> B` and `(A) -> Either<E, B>` apart at the callsites.

**Comment by raulraja** [comment]
If it's because of JVM Clash we could use @JvmName

**Comment by Hiosdra** [comment]
Shouldn't `mapEither` be named `flatMapEither`? I think `mapEither` should be more of:
```kotlin
fun <E, A> IO<E, A>.mapEither(f: (A) -> Left<E>): IO<E, A>
```
, but it does not make sense to include it in arrow in my opinon.

However, `flatMapEither` would be great 😀
---
Is any chance to make `flatMapKind` (not this naming 😝 ) which will be something of:
`Kind<F, A>.flatMapKind(A -> Kind<G, A>)`? I think of some abstraction above IO and Either. 
It could take `A -> IO`, `A -> Either`, `A -> Option` etc and will be available on any of this types, so in para-haskell way:
```
IO -> A -> IO
IO -> A -> Either
IO -> A -> Option
Either -> A -> IO
Either -> A -> Either
Either -> A -> Option
Option -> A -> IO
Option -> A -> Either
Option -> A -> Option
```

I see challange in making it work with both `Kind` and `Kind2`, but maybe it is possible?

**Comment by pakoito** [comment]
`Either` is specialised here because it'll the the most frequent use. I can see the API working for all `ApplicativeError`, although the ergonomy will be meh.

**Comment by Hiosdra** [comment]
Hi, @pakoito I didn't mean to propose `mapEither`. I meant to propose renaming `mapEither` in your proposal to `flatMapEither`, because of fact that your mapping function returns Either, like simple flatMap's mapping function on IO returns IO

**Comment by pablisco** [comment]
@raulraja 
I think until the new type inference is released with Kotlin 1.4 we are not able to use `@JvmName` to fix type erasure in this instance:
![image](https://user-images.githubusercontent.com/260697/80955547-650cd600-8df7-11ea-93d9-f7de2ee1faa5.png)
![image](https://user-images.githubusercontent.com/260697/80955758-b0bf7f80-8df7-11ea-87c0-d03e3e84064b.png)
I haven't tested the new type inference algorithm so we will have to verify it, but reducing the API surface would be a plus if we can :) Worse case, we can do something with Meta 😅

**Comment by aballano** [comment]
> Hi, @pakoito I didn't mean to propose `mapEither`. I meant to propose renaming `mapEither` in your proposal to `flatMapEither`, because of fact that your mapping function returns Either, like simple flatMap's mapping function on IO returns IO

The fact that the mapping function returns Either is stated in the name, but the rest is actually a map function, simply replace the explicit Either with some random name X and you'll see that the overall signature is more similar to map, also because the mapping function doesn't return IO.

**Comment by aballano** [comment]
Work is done thanks to @pablisco 🙌
