### ISSUE TITLE
Reduce load time for Fx main page

### ISSUE THREAD

**Issue by rachelcarmena** [arrow-kt/arrow-fx#146]
Fx main page https://arrow-kt.io/docs/next/fx/ has a higher load time compared with other pages.

After looking at it, there are 2 code snippets to show wrong code and compilation failures which include more than 2 thousand lines with multiple span sections.

Let's remove the execution for both code snippets and show the compilation error in a short format.

**More details**: comments at https://github.com/arrow-kt/arrow-site/issues/27

**Comment by calvellido** [comment]
Let me know if I can help you with this

**Comment by rachelcarmena** [comment]
> Let me know if I can help you with this

Thanks! It's done in #147
