### ISSUE TITLE
["Request"] Integration with Google Play Services Tasks API

### ISSUE THREAD

**Issue by nomisRev** [arrow-kt/arrow-fx#154]
What would you like to see?

A  Google Play Services Tasks implementation for `F` or `IO`.

See [KotlinX Coroutine Play Services](https://github.com/Kotlin/kotlinx.coroutines/tree/master/integration/kotlinx-coroutines-play-services)  for an example implementation.

**Comment by pakoito** [comment]
IMO out of scope for fx, incubation maybe.

` good first issue` a bit optimistic hahahaha

**Comment by nomisRev** [comment]
This could easily be added as a micro lib, no? KotlinX Coroutines integration also only has 2 functions.

> good first issue a bit optimistic hahahaha
😁

**Comment by nomisRev** [comment]
Obsolete by KotlinX Coroutines
