### ISSUE TITLE
["BUG"] Schedule.never

### ISSUE THREAD

**Issue by nomisRev** [arrow-kt/arrow-fx#174]
What version are you currently using?

`0.10.5`

What would you like to see?

`Schedule.never` should wait forever like all other `F` `never` operators.

[Fixed Arrow Fx Coroutines source](https://github.com/arrow-kt/arrow-fx/blob/369aea0115a8368ab3fef2a48a00ada76fa1c0df/arrow-fx-coroutines/src/main/kotlin/arrow/fx/coroutines/Schedule.kt#L622)

[Broken Arrow Fx source](https://github.com/arrow-kt/arrow-fx/blob/master/arrow-fx/src/main/kotlin/arrow/fx/Schedule.kt#L713)

**Comment by aballano** [comment]
@nomisRev the problem here with never is that in the Coroutines impl you're able to pass a never like `invoke(suspend { arrow.fx.coroutines.never<Unit>() })` but AFAIK we cannot do that right now with Monad but rather Async, no?

**Comment by nomisRev** [comment]
We have a constraint of `MonadDefer` for `jitterred`. We should do the same here for `never`.
