### ISSUE TITLE
Rx race conditions

### ISSUE THREAD

**Issue by i-walker** [arrow-kt/arrow-fx#19]
### Bug
Simon:
> There seems to be a race condition we're running into where Rx accepts the error while we're canceling. As a result the error will not be received and is logged instead.
These logs vary in length depending on how much we hit that race condition in places like `fa.startFiber(ctx).flatMap { (_, cancel) -> cancel }` where `fa` can run into an error between start and immediate cancel.

One possible way to tackle this is to turn of the RxPlugin logging for UnderliverableException. 

#### current state of art
This problem contributes to random build failures in CI/CD

**Comment by nomisRev** [comment]
Closed due to obsolete
