### ISSUE TITLE
CoroutineContext.effect doesn't switch back to caller thread

### ISSUE THREAD

**Issue by aballano** [arrow-kt/arrow-fx#22]
Maybe this is a self-assumption but I think it would be really helpful to avoid multiple thread switches, specially on "UI-driven" frameworks such as Android.

Quick example, having:

```kotlin
private suspend fun printCurrentThread() {
    println(Thread.currentThread().name)
}

val result1 = fx {
    !effect { printCurrentThread() }
    !NonBlocking.effect { printCurrentThread() }
    !effect { printCurrentThread() }
}

fun main() {
    unsafe { runBlocking { result1 } }
}
```

At least from a newbie point of view I'd expect the output to be (when called from the main thread):

```
main
ForkJoinPool-1-worker-1
main
```

But actually is:

```
main
ForkJoinPool-1-worker-1
ForkJoinPool-1-worker-1
```

This is due to the `effect` ext fun behaving similarly to `continueOn`, although I'd expect that **ideally** only the lambda inside is executed in the `NonBlocking` context and then returning to the caller context (`main` in this case).

**Comment by nomisRev** [comment]
Closed due to obsolete
