### ISSUE TITLE
Gradle sync fails on IntelliJ

### ISSUE THREAD

**Issue by pablisco** [arrow-kt/arrow-fx#234]
When opening the `arrow-fx` repo on IntelliJ this message shows when syncing:

```
Cannot convert string value 'JETPACK_COMPOSE' to an enum value of type 'com.android.builder.model.AndroidGradlePluginProjectFlags$BooleanFlag' (valid case insensitive values: APPLICATION_R_CLASS_CONSTANT_IDS, TEST_R_CLASS_CONSTANT_IDS, TRANSITIVE_R_CLASS)
```

IntelliJ IDEA version: 2020.1 (Ultimate)

This may be due to a mismatch of Android Gradle plugins and the Android IDE plugin. 
I'm not entirely sure as it works on Android Studio.

### Discussion/Opinion
Having Android dependencies on this repository adds extra build time and potential problems like these :) 
I suggest we move all android related things elsewhere.

**Comment by aballano** [comment]
This was tackled by @rachelcarmena one week ago, you can check it here: https://github.com/arrow-kt/arrow/blob/master/docs/libraries/how-to-build-a-library.md#requirements

Regarding moving arrow-fx-android elsewhere, we can consider it if becomes a burden for the lib. In any case the fx lib is growing a lot recently so we might need to consider this anyway.
