### ISSUE TITLE
["Request"] Stream adapters and examples for Android

### ISSUE THREAD

**Issue by aballano** [arrow-kt/arrow-fx#238]
What would you like to see?

LiveData-alike operators
Docs/examples on how to use Stream on Android

**Comment by JorgeCastilloPrz** [comment]
This is linked to #282

**Comment by LordRaydenMK** [comment]
This is also obsolete right? Cc @nomisRev

**Comment by nomisRev** [comment]
Yes, correct @LordRaydenMK!
