### ISSUE TITLE
Stream.filterNull semantics

### ISSUE THREAD

**Issue by pablisco** [arrow-kt/arrow-fx#241]
The extension function `Stream.filterNull()` should probably be called `filterNotNull`. Similar to what they do in [`stdlib`](https://kotlinlang.org/api/latest/jvm/stdlib/kotlin.collections/filter-not-null.html)

The word filter is very ambiguous (as many English words) but with these type of operations it's generally short for "filter in { x }" and not "filter out { x }".

While here, maybe we could rename `Stream.filterOption` into `Stream.filterSome`?

**Comment by nomisRev** [comment]
You're 100% correct!

I think the naming for `Option` is correct, since it filters the `Option` out of it.
Similarly to how it filters `?` out of the type.
