### ISSUE TITLE
Consider an Android ArchitectureComponents module

### ISSUE THREAD

**Issue by pakoito** [arrow-kt/arrow-fx#28]
https://developer.android.com/topic/libraries/architecture

**Comment by aballano** [comment]
[According to the docs](https://developer.android.com/topic/libraries/architecture/livedata), the only thing LiveData seems to bring on top of other Streams such as  Flow, Observable, etc is that it's "lifecycle aware":

> LiveData considers an observer, which is represented by the Observer class, to be in an active state if its lifecycle is in the STARTED or RESUMED state. LiveData only notifies active observers about updates. Inactive observers registered to watch LiveData objects aren't notified about changes.
>
> You can register an observer paired with an object that implements the LifecycleOwner interface. This relationship allows the observer to be removed when the state of the corresponding Lifecycle object changes to DESTROYED. This is especially useful for activities and fragments because they can safely observe LiveData objects and not worry about leaks—activities and fragments are instantly unsubscribed when their lifecycles are destroyed.

Which essentially means that it receives a [`LifecycleOwner`](https://developer.android.com/reference/android/arch/lifecycle/LifecycleOwner) as a parameter and buffers one or many (not sure tbh) emitted values during Activity rotation.

So one thing we could do is to try to add this functionality by composing the future Arrow's Stream with this similarly as we did with IO and scoping with coroutines.

--

Similarly, we could investigate if there's a real need for ViewModel as well, in case we can improve something there.

**Comment by aballano** [comment]
Closing for #26
