### ISSUE TITLE
Stream.callback's emit fails with ambiguous definition when emiting certain types

### ISSUE THREAD

**Issue by aballano** [arrow-kt/arrow-fx#281]
Currently there's a problem when trying to emit types like a List from [the `Stream.callback { emit() }` call](https://github.com/arrow-kt/arrow-fx/blob/master/arrow-fx-coroutines/src/main/kotlin/arrow/fx/coroutines/stream/callbacks.kt#L17), as it finds multiple functions with the same type, specifically these 3:

```
  fun emit(a: A): Unit
  fun emit(iterable: Iterable<A>): Unit
  fun emit(vararg aas: A): Unit
```

My suggestion would be to switch to only 2 functions, and change the multi emission name to `emits` so I'd suggest going for:

```
fun emit(a: A): Unit
fun emits(iterable: Iterable<A>): Unit
```
Pros: Straightforward to use with list
Cons: Multiple variables need to call `listOf`

The alternative version with `fun emits(vararg aas: A): Unit` could cause problems when passing a List without the spread operator `*` as it could potentially be considered a single item.

**Comment by nomisRev** [comment]
Obsolete by deprecation
