### ISSUE TITLE
["Request"] Add Jetpack Compose integration for Streams

### ISSUE THREAD

**Issue by JorgeCastilloPrz** [arrow-kt/arrow-fx#282]
What version are you currently using?

0.11.0

What would you like to see?

We could (actually should imho) have a Jetpack Compose integration module where we provide an adapter to make any `Stream` be consumable as a Jetpack Compose `State`. Something like:

```kotlin
/**
 * Uses the drain terminal operator to consume values from this [Stream] and represents its latest
 * value via [State]. Every time there would be new value posted into the [Stream] the returned
 * [State] will be updated causing recomposition of every [State.value] usage.
 *
 * @param initial value for the [State].
 */
@Composable
fun <T> Stream<T>.drainAsState(
  initial: T
): State<T> {
  val state = remember { mutableStateOf(initial) }
  launchInComposition {
    evalOn(ComputationPool) { // the pool is passed as an argument for the Flow one, we might want to do that
      this@drainAsState.effectTap { state.value = it }.drain()
    }
  }
  return state
}

```

This specific implementation mimicks [the one used for kx Coroutines Flow](https://android-review.googlesource.com/c/platform/frameworks/support/+/1381219).

I got this working in local. If we provide this integration, anybody could encode Android apps as a composition of functional streams and rely on Compose for the UI.

**Comment by nomisRev** [comment]
Obsolete by deprecation
