### ISSUE TITLE
["Request"] Stream API bridging with Either

### ISSUE THREAD

**Issue by aballano** [arrow-kt/arrow-fx#283]
When having a Stream of Eithers `Stream<Either<...>>` it would be useful to have some APIs or maybe examples about how to treat the Left case of the Either as an error (like with `handleErrorWith`)

One option that comes to my mind is to have an `unattempt` function inverse to `attempt` so we can easily convert a left side on a Throwable and back:

```
fun <E> Stream<Either<E, O>>.unattempt(f: (E) -> Throwable): Stream<O>
```

cc @JorgeCastilloPrz

**Comment by nomisRev** [comment]
Closed due to obsolete
