### ISSUE TITLE
["Request"] Debouncer operator for Streams

### ISSUE THREAD

**Issue by pablisco** [arrow-kt/arrow-fx#290]
What version are you currently using?

0.11-SNAPSHOT

What would you like to see?

The `Stream` API could implement a debouncer operator.

Suggestion:
Make sure that we wait for a given duration. the strategy could be implemented as an alias of (O) -> Boolean as used in `debounceUntil`
``` kotlin
fun Stream<O>.debounce(
  duration: Duration, 
  strategy: DebounceStrategy = DebounceStrategies.KeepLast // Could also have KeepFirst
)
```
This could be used to denounce until a condition is met, like:
```kotlin
clicks.debounceUntil { text -> text.size() >=3 } // for an input field
```
This could be derived from denounce with duration as 0:
```kotlin
fun Stream<O>.debounceUntil(condition: (O) -> Boolean)
```

**Comment by raulraja** [comment]
Thanks @pablisco, can you provide an example use case on how this is useful and how it will be used in the Streams public API?

**Comment by pablisco** [comment]
The first one can be used to avoid multiple clicks on a button. The second one can be used to have conditions, like the length of the text the user has typed. This one could be done with filter, maybe 🤔

**Comment by nomisRev** [comment]
@raulraja `debounce` is a term used by ReactiveX for throttling throughput if I'm not mistaken. Throttling can be done with different strategies like buffering, dropping, sliding, etc.


`clicks.debounceUntil { text -> text.size() >=3 } // for an input field` should be a simple `filter`, no?

**Comment by 1Jajen1** [comment]
`debounce` afaik cannot easily be modeled by our current ops since we have no way to buffer/drop elements based on the time they are pushed to the stream right?

`debounceUntil` will behave like `filter` if the strategy is `KeepLast` but may behave different with other strategies although in this case regardless of strategy `filter` will be exactly the same.

**Comment by pablisco** [comment]
I think `debounce` could be implemented in a similar fashion to `interruptWhen` but the other way around :) Other option may be to have a stateful object that filters based on an internal ticker.

Will need to investigate a bit more to see what we can do.

And yeah, `debounceUntil` is totally a filter 😅  And I guess `debounce` could be done based on filter 🤔

**Comment by nomisRev** [comment]
Stream is an implementation of FS2 on top of Arrow Fx Coroutines instead of on top of `IO` (or rather `F`). So most operators have identical implementations to FS2. See FS2's [debounce](https://github.com/typelevel/fs2/blob/main/core/shared/src/main/scala/fs2/Stream.scala#L672)

**Comment by nomisRev** [comment]
Closed due to obsolete
