### ISSUE TITLE
Stream.cancellable always runs in ComputationPool

### ISSUE THREAD

**Issue by JorgeCastilloPrz** [arrow-kt/arrow-fx#295]
What version are you currently using?

0.11.0

What would you like to see?

It'd be desirable to be able to pass specific `CoroutineContext` to `Stream.callback` and `Stream.cancellable`, given those always run on the `ComputationPool` now (via `ForkAndForget` in the `bracketCase`) and that doesn't work in Android for wrapping Android callbacks. Android callbacks are called in the UI thread the big majority of the time, and many times you get compile time errors by the system like this when trying to create the `Stream.cancellable`:

```
...
 Caused by: java.lang.IllegalStateException: Method addObserver must be called on the main thread
```

A usual example to reproduce this:

```kotlin
fun Fragment.lifecycleDestroy(): Stream<Boolean> = Stream.cancellable {
  val lifecycleObserver = LifecycleEventObserver { _, event ->
    if (event == Lifecycle.Event.ON_DESTROY) {
      emit(true)
    }
  }

  viewLifecycleOwner.lifecycle.addObserver(lifecycleObserver)
  CancelToken { viewLifecycleOwner.lifecycle.removeObserver(lifecycleObserver) }
}
```

**Comment by aballano** [comment]
Hi @JorgeCastilloPrz I'm not 100% sure as I'm doing a quick try, but I hope https://github.com/arrow-kt/arrow-fx/pull/296 should fix the issue if all tests pass. Also we might need to add one test for the bug itself.

**Comment by nomisRev** [comment]
Closed due to obsolete
