### ISSUE TITLE
Tests hangs with `evalOn` in intellij and gradle when ktor client throws exception

### ISSUE THREAD

**Issue by satyamagarwal** [arrow-kt/arrow-fx#305]
When `ConnectException` is thrown from ktor client, the evalOn hangs, even when wrapped in Either.catch. 

https://github.com/satyamagarwal/arrow-issues/blob/master/src/test/kotlin/com/arrow/issues/KtorClientTest.kt

**Comment by nomisRev** [comment]
I was debugging and saw that it was looping recursively forever in KotlinX Coroutine Core [here](https://github.com/Kotlin/kotlinx.coroutines/blob/master/kotlinx-coroutines-core/jvm/src/debug/internal/DebugProbesImpl.kt#L393).

**Comment by satyamagarwal** [comment]
So I don't have factual information on it, but usually threads hang which use `evalOn` when I run them in intellij's debug mode, they run fine without debug mode. 

I am assuming this could be the behaviour you are seeing. Debug probs shouldn't kick in in normal run, where I see the problem in the mentioned tests. What do you think ?

**Comment by nomisRev** [comment]
@satyamagarwal Aha, we've already ran into this. Here is more background, and a temporary solution for the problem.

https://kotlinlang.slack.com/archives/C5UPMM0A0/p1601883495099500

**Comment by satyamagarwal** [comment]
@nomisRev I disabled coroutine debugger like in the thread, but it still hangs.

**Comment by satyamagarwal** [comment]
@nomisRev just to add to this, in my actual application, all the tests pass that use `evalOn` except for where Api returns nothing, like in this example.

**Comment by nomisRev** [comment]
Should be fixed by #317
