### ISSUE TITLE
["Request"] User-friendlier API for Resource

### ISSUE THREAD

**Issue by nomisRev** [arrow-kt/arrow-fx#45]
Currently `Resource` only defines `operator fun invoke` to safely consume the `Resource` into a `F` program.

A more user-friendly API would be `use` analog to `fun <A : Closable> A.use` in the standard library.

Additionally, I'd be in favor of deprecating `operator fun invoke` over `use`. Operator overloading should be kept for special use-cases and I'm not sure it's really needed here over a `use` combinator.

**Comment by 1Jajen1** [comment]
I think the invoke constructors on the companion object are fine, but the override on resource should be replaced. `use` sounds good to me :+1:

**Comment by pakoito** [comment]
Why `A: Closable`?

**Comment by nomisRev** [comment]
@pakoito not a restriction of `A : Closable` on our signature but I meant to name it `use` in analog to the std function but as a functional alternative.

`public inline fun <T : Closeable?, R> T.use(block: (T) -> R): R`
