### ISSUE TITLE
Publish arrow-XXX-test modules and change the package

### ISSUE THREAD

**Issue by rachelcarmena** [arrow-kt/arrow-fx#77]
-  arrow-ank-test - it doesn't exist
- [x] arrow-core-test
- [x] arrow-fx-test
- [x] arrow-incubator-test - included in https://github.com/arrow-kt/arrow-incubator/pull/63
- [x] arrow-integrations-test - removed!  https://github.com/arrow-kt/arrow-integrations/pull/14
- [x] arrow-optics-test - it's necessary to fix the data into https://github.com/arrow-kt/arrow-optics/blob/master/arrow-optics-test/gradle.properties - https://github.com/arrow-kt/arrow-optics/pull/37
-  [x] arrow-ui-test - removed!

**Comment by aballano** [comment]
After discussing about this, we agreed that it's not a must-have for 0.10.5. The way of testing might change with Meta anyway so this will be revisited.

**Comment by danimontoya** [comment]
Do we have to re-visit all repos where we have added the flag to be published then?

**Comment by rachelcarmena** [comment]
> Do we have to re-visit all repos where we have added the flag to be published then?

It's already reviewed. I also remove arrow-test again from OSS because it was published again before fixing the data of a module.

Thank you all with this task!! :raised_hands:

**Comment by 1Jajen1** [comment]
Wait are the repos itself published or is this about changing the content of those repos?

**Comment by rachelcarmena** [comment]
> Wait are the repos itself published or is this about changing the content of those repos?

Hi @1Jajen1 !! Both of them. This task consisted on:

* Publish all the arrow test modules into OSS (into Central Maven afterwards)
* Change the package for arrow test modules in order to avoid misunderstandings.
* Improve the arrow test modules to remove unnecessary code when using `arrow-core-test` and `arrow-fx-test` dependencies mainly.

Thanks!!

**Comment by 1Jajen1** [comment]
I am just a bit confused by:
>After discussing about this, we agreed that it's not a must-have for 0.10.5. The way of testing might change with Meta anyway so this will be revisited.
What exactly does that refer to? Publishing the repos or the cleaning/restructuring/renaming?

**Comment by rachelcarmena** [comment]
> I am just a bit confused by:
> 
> > After discussing about this, we agreed that it's not a must-have for 0.10.5. The way of testing might change with Meta anyway so this will be revisited.
> 
> What exactly does that refer to? Publishing the repos or the cleaning/restructuring/renaming?

Oh, right, sorry, because we had a pending issue with one of them: `arrow-incubator-test`. It seems there were flaky tests...
