### ISSUE TITLE
["Request"] more meaningful mapping Either to 0.11.0 IO

### ISSUE THREAD

**Issue by Hiosdra** [arrow-kt/arrow-fx#9]
What version are you currently using? 0.11.0

What would you like to see?
https://kotlinlang.slack.com/archives/C5UPMM0A0/p1580384276208600

I would like to see `toIO` methods better suited for bifunctor IO

**Comment by aballano** [comment]
Hi @Hiosdra, thank you for the request! As per #175, we will be promoting the usage of coroutines via Arrow Fx Coroutines (#169), which should provide the same or even better experience than IO while interleaving much better with Either (already fixed) and other datatypes as soon as https://github.com/arrow-kt/arrow-core/issues/115 is fully implemented.

I'd recommend to try the new lib, please let us know if you find any problems or have any questions!
